name: Report
on: [repository_dispatch]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v3
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Vilicus Scan
        uses: edersonbrilhante/vilicus-github-action@feature/add-new-params
        with:
          image: "${{ github.event.client_payload.image }}"

      - name: Update report
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ${{ github.workspace }}/artifacts/results.sarif          
          
  report:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Download report
        uses: actions/download-artifact@v2
        with:
          name: results
        id: download

      - name: Save report in gitlab
        uses: ./.github/actions/report
        with:
          file: ${{steps.download.outputs.download-path}}/results.sarif
          private-token: ${{ secrets.GITLAB_PRIVATE_TOKEN }}
          project-id: ${{ secrets.GITLAB_PROJECT_ID }}
          image: ${{ github.event.client_payload.image }}