name: Vilicus Scan
on: [repository_dispatch]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v3
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Vilicus Scan
        uses: edersonbrilhante/vilicus-github-action@feature/add-new-params
        with:
          image: "${{ github.event.client_payload.image }}"

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Scan
        uses: ./
        with:
          file: "./artifacts/results.sarif"
          private-token: ${{ secrets.GITLAB_PRIVATE_TOKEN }}
          project-id: ${{ secrets.GITLAB_PROJECT_ID }}
          image: ${{ github.event.client_payload.image }}