name: Schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0,30 * * * *'
jobs:             
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run schedule jobs
        uses: ./.github/actions/schedule
        with:
          gs-spreadsheet-id: ${{ secrets.GS_SPREADSHEET_ID }}
          gs-range-name: ${{ secrets.GS_RANGE_NAME }}
          gs-credentials-info: ${{ secrets.GS_CREDENTIALS_INFO }}
          gh-url: ${{ secrets.GH_URL }}
          gh-token: ${{ secrets.GH_TOKEN }}